### ISSUE TITLE
大哥，你把mediawiki库也加上吧，我找了几个都不适合

### ISSUE THREAD

**Issue by Junland-well** [razonyang/mediawiki-zhconverter#1]

**Comment by razonyang** [comment]
composer.json 有标注 mediawiki 的版本的（1.26），你试试这个版本看看。

**Comment by razonyang** [comment]
刚测试过 1.26.1 是可以的，这个 Issue 就先关闭了。后续或许会适配更高的版本吧，不过可能性很低，毕竟对一个简繁转换库来说，Mediawiki 太“臃肿”了(80+M)。
